FROM node:16
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies - copy package.json
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
# Install all dependencies that are written in the packet.json file
RUN npm install
# Bundle app source
COPY . .
EXPOSE 3000
CMD [ "node", "index.js" ]